### ISSUE TITLE
Clients Labs

### ISSUE THREAD

**Issue by xpruimorais** [xpruimorais/SEBC#6]

**Comment by xpruimorais** [comment]
Issue: The documentation linked in the lab does not account for the existence of the Hue Balancer, so I had to check the hue `CONF_DIR` manually under `/var/run/cloudera-scm-agent/processes`, and export that path as `HUE_CONF_DIR`. This fixed the script database connection.

Also, this variables had to be set for the script to work: `HUE_SECRET_KEY=something HUE_IGNORE_PASSWORD_SCRIPT_ERRORS=1 HUE_DATABASE_PASSWORD=hue_password`.

**Comment by cfusi** [comment]
Good pass!
